CRNN:
  n_class: 4 # Deepship 의 class는 4개(cargo, passenger, tug, tanker)
  n_RNN_cell: 256
  n_RNN_layer: 2
  rec_dropout: 0
  attention: class                      # time / class

  n_input_ch: 1
  activation: cg
  conv_dropout: 0.5
  kernel_size: [ 3, 3, 3, 3, 3, 3, 3 ]
  padding: [ 1, 1, 1, 1, 1, 1, 1 ]
  stride: [ 1, 1, 1, 1, 1, 1, 1 ]
  nb_filters: [ 32, 64, 128, 256, 256, 256, 256 ]
  pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ]

  pool_dim: time 

feats:
  freq_bins : 128
  