CRNN:
  n_class: 4 # Deepship 의 class는 4개(cargo, passenger, tug, tanker)
  n_RNN_cell: 256
  n_RNN_layer: 2
  rec_dropout: 0
  attention: class                      # time / class

  n_input_ch: 1
  activation: cg
  conv_dropout: 0.5
  kernel: [ 3, 3, 3, 3, 3, 3, 3 ]
  pad: [ 1, 1, 1, 1, 1, 1, 1 ]
  stride: [ 1, 1, 1, 1, 1, 1, 1 ]
  n_filt: [ 32, 64, 128, 256, 256, 256, 256 ]
  pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ]

  n_basis_kernels: 4
  DY_layers: [ 0, 1, 1, 1, 1, 1, 1 ]
  temperature: 31
  pool_dim: time 